apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo

resources:
- ../../../../../../base/argo
# - ../../../../../../base/argo-workflows
- extensions
- workflows
- addons.applicationset.yaml

helmGlobals:
 chartHome: ../../../../../charts

helmCharts:
# https://artifacthub.io/packages/helm/argo/argo-cd
- name: argo-cd
  repo: https://argoproj.github.io/argo-helm
  version: 5.52.1
  valuesFile: ../../../../../../base/argo/values.yaml
  releaseName: argo
  includeCRDs: true
  valuesMerge: merge
  valuesInline:
    server:
      extraArgs:
      - --insecure