apiVersion: v2
name: definitions
description: definitions
type: application
version: 1.0.0

dependencies:
  # https://hub.docker.com/r/bitnami/mongodb
  - name: mongodb 
    version: 15.5.2
    repository: https://charts.bitnami.com/bitnami
