apiVersion: v2
name: definitions
description: definitions
type: application
version: 1.0.0

dependencies:
  # https://hub.docker.com/r/bitnami/mongodb
  - name: mongodb
    version: 6.2.1
    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
