service:
  type: NodePort
  ports:
  - name: status-port
    nodePort: 32701
    port: 15021
    protocol: TCP
    targetPort: 15021
  - name: http
    nodePort: 321245
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    nodePort: 32535
    port: 443
    protocol: TCP
    targetPort: 443