gateway:
  service:
    type: NodePort
    ports:
    - name: status-port
      nodePort: 32701
      port: 15021
      protocol: TCP
      targetPort: 15021
    - name: http2
      nodePort: 31245
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      nodePort: 31535
      port: 443
      protocol: TCP
      targetPort: 443