configs:
  cm:
    # Build options/parameters to use with `kustomize build` (optional)
    kustomize.buildOptions: --enable-helm --load-restrictor LoadRestrictionsNone

server:
  extensions:
    enabled: true
