apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: docker-desktop-addons
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: &repo https://github.com/ymedlop/argocd-clusters-management.git
      revision: main
      directories:
      - path: clusters/groups/localhost/docker-desktop/overlays/*
      - path: clusters/groups/localhost/docker-desktop/overlays/argocd
        exclude: true
  template:
    metadata:
      name: 'docker-desktop-{{path.basename}}'
    spec:
      project: addons
      source:
        repoURL: *repo
        path: '{{path}}'
      destination:
        name: in-cluster
        namespace: argocd
      syncPolicy:
        automated:
          prune: true