apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: docker-desktop-addons
  namespace: argocd
spec:
  generators:
  - merge:
      mergeKeys:
        - metadata.labels.env
        - path.basename
      generators:
      - matrix:
          generators:
          # enriches applications per directory in clusters/base with cluster labels
          - clusters: {}
          # produces argocd app per directory in clusters/base
          - git:
              repoURL: &repo https://github.com/ymedlop/argocd-clusters-management.git
              directories:
              - path: clusters/base/*
              - path: clusters/base/argocd
                exclude: true
      - merge:
          mergeKeys:
            - path
          generators:
          # adds env metadata from .env.yaml to each application
          # workaround for https://github.com/argoproj/argo-cd/issues/13118 - should use env directory name instead
          - git:
              repoURL: *repo
              revision: HEAD
              files:
              - path: clusters/groups/docker-desktop/.env.yaml
          # discovers environment specific applications overrides
          - git:
              repoURL: *repo
              revision: HEAD
              directories:
              - path: clusters/groups/docker-desktop/overlays/*
              - path: clusters/groups/docker-desktop/overlays/argocd
                exclude: true
  template:
    metadata:
      name: 'docker-desktop{{path.basename}}'
    spec:
      project: system
      source:
        repoURL: *repo
        path: '{{path}}'
      destination:
        server: in-cluster
        # namespace: '{{path.basename}}'
        namespace: argocd
      syncPolicy:
        automated:
          prune: true