apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
- ../../../../../base/argocd
- addons.applicationset.yaml

helmGlobals:
 chartHome: ../../../../../charts

helmCharts:
# https://artifacthub.io/packages/helm/argo/argo-cd
- name: argo-cd
  repo: https://argoproj.github.io/argo-helm
  version: 5.51.4
  valuesFile: ../../../../../base/argocd/values.yaml
  releaseName: argocd
  valuesMerge: merge
  valuesInline:
    redis-ha:
      enabled: true

    controller:
      replicas: 1

    server:
      autoscaling:
        enabled: true
        minReplicas: 2

    repoServer:
      autoscaling:
        enabled: true
        minReplicas: 2
 
    applicationSet:
      replicas: 2