micro-nodejs:
  fullnameOverride: api
  deployment:
    replicas: 1
    image:
      pullPolicy: IfNotPresent
      repository: agnjunio/albion-killbot
      tag: 4.23.4
    ports:
      - name: http
        containerPort: 80
        protocol: TCP
    command:
    - /bin/bash
    - -c
    - npm run start:api
    env:
      - name: DISCORD_TOKEN
        valueFrom:
          secretKeyRef:
            name: discord-secrets
            key: DISCORD_TOKEN
      - name: DISCORD_CLIENT_ID
        valueFrom:
          secretKeyRef:
            name: discord-secrets
            key: DISCORD_CLIENT_ID
      - name: DISCORD_CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: discord-secrets
            key: DISCORD_CLIENT_SECRET
      - name: RABBITMQ_URL
        value: amqp://rabbitmq
      - name: MONGODB_URL
        value: mongodb://mongodb:27017/albion-killbot

  service:
    ports:
      - name: http-80
        port: 80
        protocol: TCP
        targetPort: http