apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addons
spec:
  generators:
  - matrix:
      generators:
      - clusters:
          selector:
            matchLabels:
              argocd.argoproj.io/secret-type: cluster
      - git:
          repoURL: &repo https://github.com/ymedlop/argocd-clusters-management.git
          revision: &branch main
          directories:
          - path: clusters/groups/on-prem/dev/*/overlays/*
          - path: clusters/groups/on-prem/dev/*/overlays/argo
            exclude: true
  template:
    metadata:
      name: '{{name}-{{path.basename}}'
    spec:
      project: addons
      source:
        repoURL: *repo
        targetRevision: *branch
        path: '{{path}}'
      destination:
        name: '{{name}'
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true