apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
- ../../../../../../base/argocd
- applicationset.yaml

helmGlobals:
 chartHome: ../../../../../charts

helmCharts:
# https://artifacthub.io/packages/helm/argo/argo-cd
- name: argo-cd
  repo: https://argoproj.github.io/argo-helm
  version: 5.52.1
  valuesFile: ../../../../../../base/argocd/values.yaml
  releaseName: argocd
  includeCRDs: true
  valuesMerge: merge
  valuesInline:
    server:
      extraArgs:
      - --insecure