apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kazan01-apps
  namespace: argocd
spec:
  generators:
  - merge:
      mergeKeys:
        - metadata.labels.env
        - path.basename
      generators:
      - matrix:
          generators:
          # enriches applications per directory in clusters/base with cluster labels
          - clusters: {}
          # produces argocd app per directory in clusters/base
          - git:
              repoURL: &repo https://github.com/ymedlop/argocd-clusters-management.git
              revision: main
              directories:
              - path: clusters/addons/*
              - path: clusters/addons/argocd*
                exclude: true
      - merge:
          mergeKeys:
            - path
          generators:
          # adds env metadata from .env.yaml to each application
          # workaround for https://github.com/argoproj/argo-cd/issues/13118 - should use env directory name instead
          - git:
              repoURL: *repo
              revision: HEAD
              files:
              - path: clusters/groups/k3d-dev/.env.yaml
          # discovers environment specific applications overrides
          - git:
              repoURL: *repo
              revision: HEAD
              directories:
              - path: clusters/groups/k3d-dev/*
  template:
    metadata:
      name: 'kazan01-{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: *repo
        path: '{{path}}'
      destination:
        server: '{{server}}'
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true