micro-nodejs:
  fullnameOverride: crawler
  deployment:
    replicas: 1
    image:
      pullPolicy: IfNotPresent
      repository: agnjunio/albion-killbot
      tag: 4.23.3
    command:
    - /bin/bash
    - -c
    - npm run start:crawler
    env:
      - name: MONGODB_URL
        value: mongodb://mongodb:27017/albion-killbot
      - name: AMQP_URL
        value: amqp://rabbitmq