apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
- ../../../../../base/argo
- ../../../../../base/argocd-workflows
- addons.applicationset.yaml

helmGlobals:
 chartHome: ../../../../../charts

helmCharts:
# https://artifacthub.io/packages/helm/argo/argo-cd
- name: argo-cd
  repo: https://argoproj.github.io/argo-helm
  version: 5.51.4
  valuesFile: ../../../../../base/argo/values.yaml
  releaseName: argo
  valuesMerge: merge
  valuesInline:
    server:
      extraArgs:
      - --insecure
# https://artifacthub.io/packages/helm/argo/argo-workflows
- name: argo-workflows
  repo: https://argoproj.github.io/argo-helm
  version: 3.5.3
  valuesFile: ../../../../../base/argo-workflows/values.yaml
  releaseName: argo-workflows