apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: mongodb
    app.kubernetes.io/instance: mongodb
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/name: mongodb
    argocd.argoproj.io/instance: in-cluster-albion-killbot-mongodb
  name: mongodb
spec:
  replicas: 1
  selector:
    app.kubernetes.io/name: mongodb
  template:
    metadata:
      labels:
        app.kubernetes.io/component: mongodb
        app.kubernetes.io/instance: mongodb
        app.kubernetes.io/managed-by: argocd
        app.kubernetes.io/name: mongodb
        argocd.argoproj.io/instance: in-cluster-albion-killbot-mongodb
    spec:
      volumes:
        - name: mongodb-data
          emptyDir: {}
      containers:
        - name: mongodb
          ports:
            - name: mongodb
              containerPort: 27017
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: mongodb-data
              mountPath: /var/lib/mongodb/data
          image: 'registry.access.redhat.com/rhscl/mongodb-36-rhel7:1-5'