apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: mongodb
    app.kubernetes.io/instance: mongodb
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/name: mongodb
    argocd.argoproj.io/instance: in-cluster-albion-killbot-mongodb
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mongodb
  template:
    metadata:
      labels:
        app.kubernetes.io/component: mongodb
        app.kubernetes.io/instance: mongodb
        app.kubernetes.io/managed-by: argocd
        app.kubernetes.io/name: mongodb
    spec:
      volumes:
        - name: mongodb-data
          emptyDir: {}
        - name: mongodb-config
          emptyDir: {}
      containers:
        - name: mongodb
          ports:
            - name: mongodb
              containerPort: 27017
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
            - name: mongodb-config
              mountPath: /data/configdb
          image: "mongo:4.4"
          readinessProbe:
            exec:
              command:
                - echo 'db.runCommand("ping").ok' | mongo mongodb:27017/test --quiet
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 30
          livenessProbe:
            exec:
              command:
                - echo 'db.runCommand("ping").ok' | mongo mongodb:27017/test --quiet
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 30