apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    name: mongodb
  template:
    metadata:
      labels:
        name: mongodb
    spec:
      volumes:
        - name: mongodb-data
          emptyDir: {}
      containers:
        - name: mongodb
          ports:
            - name: mongodb
              containerPort: 27017
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: mongodb-data
              mountPath: /var/lib/mongodb/data
          image: 'registry.access.redhat.com/rhscl/mongodb-36-rhel7:1-5'