micro-nodejs:
  fullnameOverride: bot
  deployment:
    replicas: 1
    image:
      pullPolicy: IfNotPresent
      repository: agnjunio/albion-killbot
      tag: 4.23.4
    command:
    - /bin/bash
    - -c
    - npm run start:bot
    env:
      - name: DISCORD_TOKEN
        valueFrom:
          secretKeyRef:
            name: discord-secrets
            key: DISCORD_TOKEN
      - name: MONGODB_URL
        value: mongodb://mongodb:27017/albion-killbot
      - name: RABBITMQ_URL
        value: amqp://rabbitmq