apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
- extension.yaml

helmGlobals:
  chartHome: ../../charts

helmCharts:
# https://artifacthub.io/packages/helm/argo/argo-rollouts
- name: argo-cd
  repo: https://argoproj.github.io/argo-helm
  version: 2.26.0
  valuesFile: values.yaml