apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: amqp
    app.kubernetes.io/instance: amqp
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/name: amqp
    argocd.argoproj.io/instance: in-cluster-albion-killbot-amqp
  name: amqp
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: amqp
  template:
    metadata:
      labels:
        app.kubernetes.io/component: amqp
        app.kubernetes.io/instance: amqp
        app.kubernetes.io/managed-by: argocd
        app.kubernetes.io/name: amqp
    spec:
      volumes:
        - name: amqp
          emptyDir: {}
      containers:
        - name: amqp
          ports:
            - name: amqp
              containerPort: 15672
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: amqp
              mountPath: /var/lib/lavinmq
          image: "rabbitmq:3-management"