apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: amqp
    app.kubernetes.io/instance: amqp
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/name: amqp
    argocd.argoproj.io/instance: in-cluster-albion-killbot-amqp
  name: amqp
spec:
  ports:
    - name: amqp
      port: 15672
      protocol: TCP
      targetPort: amqp
  selector:
    app.kubernetes.io/component: amqp
    app.kubernetes.io/instance: amqp
    app.kubernetes.io/name: amqp
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
