apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: datadog

helmGlobals:
 chartHome: ../../../../../charts

helmCharts:
# https://artifacthub.io/packages/helm/datadog/datadog
- name: datadog
  repo: https://helm.datadoghq.com
  version: 3.66.0
  valuesFile: ../../../../../base/datadog/values.yaml
  releaseName: datadog