apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd-rollouts

resources:
- ../../../../../base/argo-rollouts

helmGlobals:
 chartHome: ../../../../../charts

helmCharts:
# https://artifacthub.io/packages/helm/argo/argo-rollouts
- name: argo-rollouts
  repo: https://argoproj.github.io/argo-helm
  version: 2.32.4
  valuesFile: ../../../../../base/argo-rollouts/values.yaml
  releaseName: argo-rollouts
  valuesMerge: merge
  valuesInline:
    dashboard:
      enabled: true