apiVersion: v2
name: definitions
description: definitions
type: application
version: 1.0.0

dependencies:
  # https://ymedlop.github.io/micro-helm-charts
  - name: micro-nginx
    version: 1.0.3
    repository: https://ymedlop.github.io/micro-helm-charts