apiVersion: argoproj.io/v1alpha1
kind: ArgoCDExtension
metadata:
  name: argo-rollouts
  namespace: argocd
  finalizers:
    - extensions-finalizer.argocd.argoproj.io
spec:
  sources:
  - web:
      url: https://github.com/argoproj-labs/rollout-extension/releases/download/v0.3.3/extension.tar