apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argo-cert
spec:
  secretName: argo-cert
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
  dnsNames:
  - argo.docker-desktop.com