apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: k8scicd-cert
spec:
  secretName: k8scicd-cert
  issuerRef:
    name: selfsigned
    kind: Issuer
  subject:
    organizations:
    - cluster.local
    - cert-manager
  commonName: "argocd.k8scicd.dev"
  dnsNames:
  - "argocd.k8scicd.dev"