apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: k8scicd-cert
spec:
  secretName: k8scicd-cert
  issuerRef:
    name: selfsigned
    kind: Issuer
  commonName: "*.k8scicd.dev"
  dnsNames:
  - "*.k8scicd.dev"