apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: global-gateway
spec:
  selector:
    istio: gateway
  servers:
    - hosts:
        - k8scicd.dev
      port:
        name: https
        number: 443
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: k8scicd-cert
    - hosts:
        - k8scicd.dev
      port:
        name: http
        number: 80
        protocol: HTTP
      tls:
        httpsRedirect: false