apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: global-gateway
spec:
  selector:
    istio: ingress
  servers:
    - hosts:
        - argocd.k8scicd.dev
      port:
        name: https
        number: 443
        protocol: HTTPS
      tls:
        credentialName: k8scicd-cert
        mode: SIMPLE