apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-ingress

helmGlobals:
 chartHome: ../../../../../../charts

helmCharts:
  # https://istio.io/latest/docs/setup/install/helm/
  # https://artifacthub.io/packages/helm/istio-official/gateway/1.17.1?modal=values
- name: gateway
  namespace: istio-ingress
  repo: https://istio-release.storage.googleapis.com/charts/
  version: 1.20.2
  valuesFile: ../../../../../../base/istio-ingress/values.yaml
  releaseName: gateway
  valuesMerge: merge
  valuesInline:
    service:
      type: LoadBalancer
      annotations:
        metallb.universe.tf/address-pool: custom-addresspool
      ports:
      - name: status-port
        port: 15021
        protocol: TCP
        targetPort: 15021
      - name: http2
        port: 80
        protocol: TCP
        targetPort: 80
      - name: https
        port: 443
        protocol: TCP
        targetPort: 443

resources:
- global-gateway.yaml