apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: datadog

helmGlobals:
 chartHome: ../../../../../charts

helmCharts:
# https://kiali.io/docs/installation/installation-guide/install-with-helm/
- name: datadog 
  repo: https://datadog
  version:  1.65.0
  valuesFile: ../../../../../base/datadog/values.yaml
  releaseName: datadog
