apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: k8scicd-cert
spec:
  secretName: k8scicd-cert
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
  commonName: "argo-cd.k8scicd.dev"
  dnsNames:
  - "argo-cd.k8scicd.dev"